# Generated by Django 5.2.1 on 2025-05-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_options_donation_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='project_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
