# Generated by Django 5.2.1 on 2025-06-03 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation", "0003_remove_donation_project_and_more"),
        ("projects", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="project_title",
        ),
        migrations.AddField(
            model_name="donation",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
