# Generated by Django 5.2.1 on 2025-05-29 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='projecttag',
            unique_together={('project', 'tagname')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='projects_ca_name_a58939_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='projects_pr_user_id_2b1982_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='projects_pr_categor_30f4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='projects_pr_start_d_9f6d89_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['end_date'], name='projects_pr_end_dat_f8a25b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_cancelled'], name='projects_pr_is_canc_471ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'created_at'], name='projects_pr_status_7ee874_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status'], name='projects_pr_user_id_40c3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'status'], name='projects_pr_categor_b7ef12_idx'),
        ),
        migrations.AddIndex(
            model_name='projectpic',
            index=models.Index(fields=['project'], name='projects_pr_project_0b67a6_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttag',
            index=models.Index(fields=['project'], name='projects_pr_project_d7fa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttag',
            index=models.Index(fields=['tagname'], name='projects_pr_tagname_a9680b_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttag',
            index=models.Index(fields=['project', 'tagname'], name='projects_pr_project_149e38_idx'),
        ),
    ]
