# Generated by Django 5.2.1 on 2025-06-02 01:23

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_facebook_profile_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="EG", max_length=2
            ),
        ),
    ]
